### ISSUE TITLE
[FEAT] Rename "master" branch to "main"

### ISSUE THREAD

**Issue by paescuj** [iconoir-icons/iconoir#103]
**Is your feature request related to a problem? Please describe.**

* "main" is a less offensive term than "master" (see https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main).
* "main" is now the default branch for new repositories on GitHub.
* A lot of repositories have already switched from "master" to "main".

**Describe the solution you'd like**

Rename the branch (see https://github.com/github/renaming#renaming-existing-branches, just takes a few seconds).

**Describe alternatives you've considered**

Leave it as it is.

**Additional context**

I'm not sure whether the [CSS URL](https://github.com/lucaburgio/iconoir#css) will still work after renaming, although changes are high since GitHub is configured "to redirect links that contain the deleted branch name such as master to the corresponding link in the repository's new default branch."
However using the default branch in cdn.jsdelivr.net URLs is not recommended anyway, so if this won't work I suggest to update the URL to use a specific version.

**Comment by paescuj** [comment]
@lucaburgio @sammarks What do you think about this issue? I feel like we should better address this sooner than later...

**Comment by sammarks** [comment]
We could rename it after the new website is finished; so here in the next 2 weeks.
