### ISSUE TITLE
[FEAT] Vue Library

### ISSUE THREAD

**Issue by igorer88** [iconoir-icons/iconoir#124]
**Is your feature request related to a problem? Please describe.**
There' s no Vue Library

**Describe the solution you'd like**
A Vue Component Library that could be imported as with React Library

**Describe alternatives you've considered**
I could make it and do a PR. 😄 

**Additional context**
It would be a good idea to make it compatible with both Vue 2 and Vue 3, I will have to do some investigation, but I could try it.
If it gets too much complicated, we could start with one. **(We could discuss about it)**

**Comment by lucaburgio** [comment]
Hi @igorer88,
do you still want to work on this? It would be great to have the support for Vue 🙌
@sammarks can support you in case of doubts or needs! (🙏🏻)

**Comment by igorer88** [comment]
Yes, sure. It would be great.
