### ISSUE TITLE
[ICON] Tool

### ISSUE THREAD

**Issue by luis-otvio** [iconoir-icons/iconoir#136]
Icon name: tool
Use case: for a tool menu, work orders or any general toolbox
Screenshots of similar icons:
![images](https://user-images.githubusercontent.com/25575479/160966485-841d9189-2529-4952-9362-12aac5ba205a.png)

**Comment by lucaburgio** [comment]
Solved in [v5.3](https://github.com/iconoir-icons/iconoir/releases/tag/v5.3.0)
