### ISSUE TITLE
[ICON] Reply icon

### ISSUE THREAD

**Issue by just-learning-1** [iconoir-icons/iconoir#170]
## Icon Request

* Icon name: **Reply**
* Use case: Like the Reply icon in **Mail** apps
* Screenshots of similar icons: 
<img width="138" alt="image" src="https://user-images.githubusercontent.com/91099019/173959548-3e7c1ac5-3a33-45d9-a223-f8dca51ed393.png">

The Forward icon would also be cool, just not my top need at the moment :)

Love your work, thank you!

**Comment by lucaburgio** [comment]
Thank you!
