### ISSUE TITLE
[FEAT] Solid icons

### ISSUE THREAD

**Issue by lucaburgio** [iconoir-icons/iconoir#175]
@sammarks 
I often receive requests for a solid version of Iconoir.
until now, I avoided that version because, technically speaking, it needs to be built with outlines and not with paths. This results in a less customizable icon when scaling or altering it.

Ultimately, I spent some time to figure out if there's a perfect solution, and looking around the web I came up with this:

- We could deliver a solid version based on the same grid: 24x24px, as the original one.
- If you want to use a different grid and use both of the styles, you'll see that the icons are technically scaling differently, and maybe you'll need to create your custom solid version, but if you keep our suggested grid, there are no issues at all.

See the image attached to have an idea of the differences: `Path` is the one we're currently using and the official one, `Solid` would be the new version. I would avoid creating an `Outline` style. It wouldn't solve the issue efficiently.

What do you think? @sammarks 
I would also like to know from you which could be the best way to naming those icons, and if we should separate them in different folders or not. The benefits and the downsides for the already built libraries.

![Iconoir different structure](https://user-images.githubusercontent.com/6526461/177005251-3a7926a8-4109-40bf-8bbf-cc5bed941642.png)

**Comment by sammarks** [comment]
I would assume the biggest issue you are worried about in terms of lack of customizability is, in the example above, controlling the thickness of the B in the solid style?

So basically would be controlling the thickness of interior elements.

Am I correct on that?

If so, there might be a way to solve for it via some magic with paths; I'll have to play around with it a bit though.

**Comment by lucaburgio** [comment]
Exactly, but of course, you'll have this issue only if you need to scale your icons and you want to use both styles.
I mean, maybe I'm overthinking and this could still be useful, given the fact that even now if you want a solid icon scaled you need to create it as we don't offer them.

The other solution (not sure if we're going into complexity) is to offer all of the three options `path`, `outline`, and `solid`. So, if you want to use both and scale them you gonna use outline and solid, but of course keeping in mind the scaling is quite different from the original `path` one.

**Comment by sammarks** [comment]
@lucaburgio just to make sure the current React libraries function as you intend, inside [this Sandbox](https://codesandbox.io/s/icy-wind-06qv2k?file=/index.html) (or just the screenshot below), which scaling looks correct, the first group or the second group?

![image](https://user-images.githubusercontent.com/424093/177831214-29dc6be1-bcf8-425a-8f91-c31a6620c5f9.png)

**Comment by lucaburgio** [comment]
@sammarks Initially, my answer was the second group, but then, to double-check, I played a bit with Figma, and yes, the scale with K (and not with V) reflects the same behavior of your first group, which makes sense after all (I would make that default if possible).

All of this is to say, why not, we shouldn't stress out about this diff between the two. The ones with the path are still full-customizable if someone uses the feature, otherwise, they scale exactly the same.

I would start preparing the solid version then.
Regarding the naming, what would you prefer?

- Same name but in different folders in /icons.
- Same name + suffix '-solid' (in this case we could have some problems with existing icons).

**Comment by sammarks** [comment]
Sounds good on the variants. With that said, the existing libraries should already scale how we want them to.

I would create using the same name, with the `solid` suffix on them. That seems to be what Material UI icons does, and I know Ant Icons does the same thing.

I know some icons already have the "Outline" suffix on them, but I don't think there are any with the solid suffix on them. I could be wrong though 😄

And as far as impacting current libraries, I view this as just adding 1,000 more icons to the pack. Same process, essentially.

Eventually, once we have more variants it would be cool to rework the website with different selectors for the different modes.

**Comment by lucaburgio** [comment]
There's only one icon in the 3D category with that suffix already, but we can change it and for future icons avoid similar names.

Good to me like this as we avoid splitting the icons in folders.
About Material icons, I can't see the `solid` suffix, but I see what they did in the Ant library.
I'll proceed with the `solid` version then ✅

I was thinking the same for the website. I'll write you know afaic.
Thank you Sam!

**Comment by lucaburgio** [comment]
On hold.
