### ISSUE TITLE
[FEAT] React Context for default icon props?

### ISSUE THREAD

**Issue by benslv** [iconoir-icons/iconoir#183]
**Is your feature request related to a problem? Please describe.**
Having to set the icon props for every icon individually can be time-consuming if using a lot of them in a project. Similarly, it'd also be frustrating to have to _update_ the props for every icon when you want to make a project-wide change, and you run the risk of missing some icons out simply because you didn't find them in the project.

**Describe the solution you'd like**
Create a Context Provider which can wrap the entire project and provide a user-defined set of default props that every icon consumes. Individual props could then still be passed into the icons when desired but it also enables global, project-specific defaults (e.g. strokeWidth, height, width) as well.

**Describe alternatives you've considered**
I'm not sure there are any alternatives for this proposal. Context is also used by the very popular [React Icons](https://github.com/react-icons/react-icons#configuration) library.

**Additional context**
I'd be interested in helping to implement this feature, if you decide it'd be beneficial to the project!

**Comment by sammarks** [comment]
Thanks for the suggestion! I am currently working on this in another branch with another new feature, so this should be coming soon.

**Comment by benslv** [comment]
Amazing! Looking forward to seeing it in action.
