### ISSUE TITLE
[ICON] File

### ISSUE THREAD

**Issue by lifeparticle** [iconoir-icons/iconoir#184]
## Icon Request

* Icon name: File
* Use case: File Explorer
* Screenshots of similar icons: 
![Untitled](https://user-images.githubusercontent.com/1612112/179456839-73f80289-b89f-47d5-bbf7-e4e265c5e7cd.png)

**Comment by lucaburgio** [comment]
Thank you! I'll add an additional alternative and improve the tags. You can find already a similar icon in the library, called `empty-page` 🙌

Hope this helps!

**Comment by lifeparticle** [comment]
:D Thank you, if possible, please consider adding a file icon with a plus symbol, `add-file` maybe. Something like add folder type.
![Screen Shot 2022-07-18 at 5 42 17 pm](https://user-images.githubusercontent.com/1612112/179465850-a946c529-aa5e-432d-9ad6-6c79651a552b.png)

**Comment by lucaburgio** [comment]
Will do! ✍🏻
