### ISSUE TITLE
React Native 0.70 color codes not being respected

### ISSUE THREAD

**Issue by MyPalVikram** [iconoir-icons/iconoir#198]
## Prerequisites

* Version: 5.3.0
* Are you running from source/main:
* Are you using a released build:
* Operating system: Mac OS
* Bits:

## Step to reproduce

Using any icon from the react-native package doesn't seem to respect the color code. Applied using the `color` prop. 

## Additional info or screenshots

`<Mail height={22} width={22} strokeWidth={2} color="blue" />`
<img width="56" alt="Screenshot 2022-09-16 at 1 19 41 PM" src="https://user-images.githubusercontent.com/6226652/190726234-43d5ff51-0d72-4ee5-aae2-bf3aba8ba3be.png">

`<Mail height={22} width={22} strokeWidth={2} color="black" />`
<img width="63" alt="Screenshot 2022-09-16 at 1 19 57 PM" src="https://user-images.githubusercontent.com/6226652/190726274-422111c0-df92-406c-bf73-ec5c5806187c.png">

**Comment by paescuj** [comment]
Is the icon nested in an other element which acts as a filter? It seems like the color is getting inverted somehow...

**Comment by MyPalVikram** [comment]
> 

This is the whole component:

```
        <View style={{ paddingBottom: 10 }}>
          <OutlinedButton onPress={() => navigation.navigate('LogIn')}>
            <View style={{ position: 'absolute', left: 15 }}>
              <MailSvg />
            </View>
            <View
              style={{
                flex: 1,
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
              }}>
              <CustomText text="Log in with email" />
            </View>
          </OutlinedButton>
        </View>
```

I have the same exact code running in an Expo application and no issues. Which led to me thinking it's something with the newer version.

**Comment by paescuj** [comment]
Yes, seems to work in Expo: https://snack.expo.dev/@psc/iconoir-color
Expo is currently running with version [0.69.4](https://github.com/expo/snack/blob/c107e34126c95e31a0c205e4e3516b971d1469f0/runtime/package.json#L48) of `react-native`.
However, I cannot see any relevant breaking changes in the [changelog](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#0700)...

**Comment by MyPalVikram** [comment]
Ok, it's actually `react-native-svg` version 13.2 that is breaking the color codes. Downgrading to 13.1 fixed my issue.
