### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by SiyonaL** [iconoir-icons/iconoir#199]
Hello, Myself Siyona Lodha!
I wanted to contribute to your project for my college open source lab.
Can you please assign me some tasks and give me an opportunity to become a contributor?

Thank you,
Waiting for a positive response :)

**Comment by sammarks** [comment]
👋 Hello there! We don't currently have any issues tagged as a good first issue. I would keep your eye on the issues tab and if an issue comes along marked as "good first issue," feel free to take it on.

Thanks for your interest!
