### ISSUE TITLE
[ICON] Three dots icons

### ISSUE THREAD

**Issue by justingolden21** [iconoir-icons/iconoir#203]
## Icon Request

* Icon names: Dots horizontal and dots vertical

* Use case: Smaller dropdown menus
This is my personal use case:
![image](https://user-images.githubusercontent.com/30274440/192167403-89183579-508f-4bbc-9aba-fa340d6dbe6a.png)

* Screenshots of similar icons:
See https://heroicons.dev/?query=dots
![image](https://user-images.githubusercontent.com/30274440/192167414-949707a1-e0a6-4f1a-babb-4a2ab83766e1.png)

I read icon PRs are not wanted at this time, but here's the path I use just in case it's helpful: `M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z`

**Comment by sammarks** [comment]
These icons should already be available; head to [our website](https://iconoir.com) and search for "more" inside the box.

You'll see `more-horiz`, `more-vert` and circled variants of those.
