### ISSUE TITLE
[ICON] Bolt icon

### ISSUE THREAD

**Issue by designerdada** [iconoir-icons/iconoir#204]
## Icon Request

* Icon name: Bolt
* Use case:
* Screenshots of similar icons: 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/5697992/192694033-935ebbd5-0ff9-4fd9-abbb-fc48edcfe299.png">

**Comment by lucaburgio** [comment]
The icon is already available with the tag `flash`. I'm going to add more tags for this one, including `bolt`.
Also, an update for this icon is on its way. It will simplify the icon (similar to the one you attached).

**Comment by lucaburgio** [comment]
Icon updated with release [v5.4.1](https://github.com/iconoir-icons/iconoir/releases/tag/v5.4.1)

**Comment by designerdada** [comment]
Looks good, and thank you so much! 👍
