### ISSUE TITLE
[ICON] Accessibility Icon Update

### ISSUE THREAD

**Issue by sammarks** [iconoir-icons/iconoir#207]
It looks like there's a concerted effort to update the Accessibility icon to indicate more movement.

See:

https://twitter.com/joshwcomeau/status/1582037019345432576?s=61&t=uA01Ipn3VDfSH4sGcShCdA
https://accessibleicon.org/

Here's a screenshot of the new icon:

![image](https://user-images.githubusercontent.com/424093/196237822-0f087c8c-bc77-49eb-8b2e-51cf755792bc.png)

**Comment by lucaburgio** [comment]
Super interesting, thank you for spotting it @sammarks 💪 
We should definitely follow this effort! I'll release the icon in our next minor.
