### ISSUE TITLE
Icon name inconsistency

### ISSUE THREAD

**Issue by mkukiro** [iconoir-icons/iconoir#213]
I've seen that a lot of icons have inconsistent names, such as these:

![image](https://user-images.githubusercontent.com/68143381/200169754-6d3c7c46-d29a-4981-a45e-690c05cb999c.png)
![image](https://user-images.githubusercontent.com/68143381/200169782-748ded24-830c-4897-9618-89508cc8c7e5.png)

All the icons have different names for when they are inside a circle, this also happens with squares.

**Comment by lucaburgio** [comment]
Well spotted!
I'm aware of it. This happened over the years by not having a strict naming structure. The fix will be included in the next major release `v6.0`.

**Comment by mkukiro** [comment]
I've also seen `warning` and `issue` are also inconsistent

**Comment by lucaburgio** [comment]
Thank you @mkukiro! 🙏

**Comment by lucaburgio** [comment]
Fixed in `v6.0`
