### ISSUE TITLE
[ICON] Mastodon

### ISSUE THREAD

**Issue by Mitsunee** [iconoir-icons/iconoir#214]
## Icon Request

* Icon name: Mastodon
* Use case: Social Media
* Screenshots of similar icons: See https://joinmastodon.org/branding

----------

Edit: I would highly appreciate if you could stop with the "+1" comments. They do not contribute to anything in any meaningful way. Please feel free to use the reaction below if you would like to agree with the proposal or use the subscribe button in the sidebar to subscribe to the thread.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/214">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/214/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/214/pledge.svg">
</picture>
</a>

**Comment by azat-io** [comment]
+1 for Mastodon icon

**Comment by andrew8088** [comment]
+1

**Comment by mpeanutbutter** [comment]
+1

**Comment by lucaburgio** [comment]
Added in v.7.2.0
