### ISSUE TITLE
[ICON] Minus outlined

### ISSUE THREAD

**Issue by DaniFoldi** [iconoir-icons/iconoir#225]
## Icon Request

* Icon name: `minus-circled-outline`
* Use case: There is an `add-circled-outline`, so for operations where + and - are more relevant than + and x, a circled version of `minus` would make sense. There is already a square version, and most other `-square-outline` icons have circled versions as well
* Screenshots of similar icons:

`minus-circled` from Radix Icons:
![Screenshot 2023-01-08 at 9 25 53](https://user-images.githubusercontent.com/6977583/211187048-354e3441-6035-4a9b-a2f0-51d2e4cfbabe.png)

**Comment by lucaburgio** [comment]
Thank you for spotting it Daniel!

**Comment by paescuj** [comment]
You rock, @lucaburgio 🤘😄
The icon is now available under the name `minus-circle`.
