### ISSUE TITLE
[ICON] CMD key symbol

### ISSUE THREAD

**Issue by erhankaradeniz** [iconoir-icons/iconoir#230]
## Icon Request

* Icon name: CMD key icon (apple device)
* Use case: need it for the CMD + K shortcut and want to use the symbol as icon
* Screenshots of similar icons:

**Comment by DaniFoldi** [comment]
+1 on this, here's an example screenshot from Phosphor Icons (https://phosphoricons.com), called "command":

![Screenshot 2023-01-13 at 15 55 37](https://user-images.githubusercontent.com/6977583/212349941-846f50ec-9b16-418a-9d68-8e260e0d337e.png)
