### ISSUE TITLE
Missing icon: remove-user

### ISSUE THREAD

**Issue by emiliodavidcs** [iconoir-icons/iconoir#235]
## Prerequisites

* Version: v6.0.0
* Are you running from source/main: yes
* Are you using a released build: no
* Operating system: MacOS
* Bits: not sure what this means, sorry

## Step to reproduce

In an HTML document, link the CDN version of the library
`<link
	rel="stylesheet"
	href="https://cdn.jsdelivr.net/gh/lucaburgio/iconoir@main/css/iconoir.css"
/>`

Then create an icon with "remove-user" icon
`
<i class="iconoir-remove-user"></i>
`

The icon should appear on the page

## Actual behavior

Icon is not shown

**Comment by sammarks** [comment]
Thanks for the report! It looks like we don't currently have an icon for removing a user.

If you would like to request a new icon, do you mind creating a new issue using the icon request form instead of the bug report form?

**Comment by sammarks** [comment]
Thanks for the report!

It looks like the CSS file you are using is from the old repository, and we have since renamed it to be in its own GitHub organization.

Here's the new CSS URL:

```

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css">
```
