### ISSUE TITLE
Search Icon looks a lot smaller than other icons with same size

### ISSUE THREAD

**Issue by MyPalVikram** [iconoir-icons/iconoir#236]
* Version: 6.0.0

I've noticed that the Search icon is a lot smaller than the others when they all have the same size.

<img width="401" alt="Screenshot 2023-01-25 at 1 33 01 PM" src="https://user-images.githubusercontent.com/6226652/214695958-c00d0706-3f60-4079-8c92-e12f974d01d2.png">

**Comment by lucaburgio** [comment]
Thank you for spotting this @MyPalVikram 
It will be fixed soon in `6.1.1`

**Comment by lucaburgio** [comment]
`6.1.1` has been released.
