### ISSUE TITLE
👨‍🚀 Compatibility with Astro

### ISSUE THREAD

**Issue by pheralb** [iconoir-icons/iconoir#238]
## Prerequisites

* Version: **6.1.1**
* Using: **Astro + React + Typescript**
* Operating system: **Windows 11**

## Step to reproduce

- Create a new component with Iconoir icon:
```jsx
import { GitHub } from "iconoir-react";

const WithIconoirIcon = () => {
  return (
    <GitHub width={23} height={23} />
  )
}

export default WithIconoirIcon
```
- Import in a Astro file:

```astro
---
import WithIconoirIcon from "../components/withIconoiricon";
---

<WithIconoirIcon />
```
- Running ``npm run dev`` works but if you run ``npm run build`` it shows the following error:

```bash
 generating static routes
 error   Named export 'GitHub' not found. The requested module 'iconoir-react' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:

  import pkg from 'iconoir-react';
  const { Twitter, GitHub, LinkedIn, Heart, OpenNewWindow, Npm, Puzzle } = pkg;
```

## Additional info or screenshots:

![image](https://user-images.githubusercontent.com/62877300/215300678-237ee5b1-c22c-4b53-91b1-d0b95dff8b92.png)

**Comment by sammarks** [comment]
🎉 Fixed in v6.2.0
