### ISSUE TITLE
Icon naming conventions

### ISSUE THREAD

**Issue by DaniFoldi** [iconoir-icons/iconoir#251]
Hi 👋 ,

## Prerequisites

* Version: 6.3.0
* Are you running from source/main: it should be the same right now anyways
* Are you using a released build: latest release, 6.3.0
* Operating system: macOS 13

## Step to reproduce

- Check the list of icon names
- All of them are dashed

### Actual behavior

- Observe that "privacy policy" is the only one with a space in the file name

## Additional info or screenshots

Commit: https://github.com/iconoir-icons/iconoir/commit/45bb8946983c1816c63b43a3cd177d454e067425#diff-23481460468784d641255a1951dc9ad1718cb071ed79082f639bf7ff03d6222d

I understand that renaming it would be a somewhat breaking change, so the solution could be to duplicate/alias the file as `privacy-policy`. Based on the feedback on this issue, I have noticed a few other inconsistencies remaining in v6:
- `cancel` and `delete-circle`
-  `load-action-floppy`, `save-action-floppy` but `save-floppy-disk`
- most icons that have boxed versions are `-square`, but `fast-arrow-right-box` as well as other directions
- most arrows are named `{type-}arrow-{dir}{-style}`, but `down-round-arrow` has the naming flipped
- `album` and `album-open`, but `mail-opened`
- the new `slash` icon (many thanks for that) and poor `git-command` instead of `slash-square`

Sorry 😅

**Comment by lucaburgio** [comment]
Thank you for spotting all of these!

- 👉 'privacy policy`: First time it has happened, and it is not good. Let's fix this with the least disruption possible. Open for feedback. Go to go with this solution if we want to push that now.

> so the solution could be to duplicate/alias the file as privacy-policy.

Otherwise, if we go with a major release, we can directly rename it.

- 👉 For all the others, I'll check them case by case, but what you're saying makes total sense. I'm already noticing a couple of them that should have been included in the last effort I made about consistency in the naming. Thank you for spotting those @DaniFoldi.

@sammarks Any thoughts on these points (especially the `policy` one?

**Comment by sammarks** [comment]
If we're doing any large scale renames (in bulk), then a major version is the best approach along with renaming all of them at once.

I would continue to gather feedback on the most consistent way of naming these and then make another major release with all of the renames done at once.

We should probably write down naming conventions somewhere too in order to help with naming new icons in the future.

**Comment by lucaburgio** [comment]
Agree. I'll look into the list @DaniFoldi wrote, and I'll double-check the library for any other possible icons with the same issues.
When ready, I'll prepare a `v7.0.0` with all of these changes.

Agree on writing down the naming convention. The reminders on my mac are probably not enough 😅.

Thank you both. Meanwhile, feel free to continue the thread for any updates on the matter.

**Comment by DaniFoldi** [comment]
Thanks for your feedback!

Here are few other ones - the more I include here, the more we'll get right next time 😁. I'll just include the renaming I think would make sense, feel free to name it something else:
- `settings-cloud` -> `cloud-square`
- `private-wifi` -> `wifi-lock` ?
- `wifi-error` -> ?
- `ar-symbol` -> `ar-tag`
- `vr-symbol` -> `vr-tag`
- `clean-water` -> `water-check`
- all `-check` -> `-success` ? - the x ones are called error, this one might have counterarguments that I don't know, or `voice-ok`
- `gas-tank-drop` -> `gas-tank-droplet`
- `add-folder` -> `folder-add`
- `remove-folder` -> `folder-remove`
- `text-alt` -> `text-square`
- `search-font` -> `text-search`
- send & receive currencies
- `coin` -> `dollar-circle` (& others, see below)
- `hospital-sign` -> `hospital-circle`
- `voice-phone` -> `phone-voice`
- `bookmark-empty` -> `bookmark`
- `fx` `hd` `gps` and `hdr`, although creating a `-tag` alternative is probably the right solution, as they are not "tags" like others
- `closed-captions` -> `closed-captions-tag`
- science letters, and `cooling`
- `ip-address` -> `ip-address-tag`
- `remove-from-cart` -> `card-remove`
- `add-to-card` -> `cart-add` (also the regular `cart` icon or `cart-alt` doesn't match)
- `bin-minus` -> `bin-remove`
- `green-` -> `-green`
- various `-remove`, `-error`, `-issue`, `no-access` and `-delete` icons with x ! and -, and card icons specifically
- `eye-off` -> `eye-disabled`
- `info-empty` -> ?
- `network-alt` -> ?
- `card-security` -> `card-secure`
- `selection`

Since first opening this issue I also noticed that there are - let's say - missing icons, or incomplete icon sets. I like the idea @sammarks to keep track of naming conventions, especially for "actions", some icons have add, but no remove variant, etc.

Additionally, some icons have circle, but no square outline variants (or vice versa). Since neither of those wouldn't be breaking changes to add more _combinations_, I didn't mention them in the original description.

Arranging them in a table might make it easier to follow the naming scheme. 

_Additional minor visual inconsistencies that I found that are unrelated, and not (yet) worth opening a separate issue for: `cloud` icons are the only ones where the action is centered horizontally, `pharmacy-cross-square` is more rounded than other squares._

I have also found some incomplete icon sets, such as card suits, chess pieces, PlayStation buttons (since we have Xbox), a trademark (TM) icon, plug types (general outlet & EV?)


Wow, this is a rather lengthy list, I apologise again :sweat_smile:. Please don't release 7.0.0 immediately, I'm sure I'll find more if I do another pass.

**Comment by sammarks** [comment]
Thank you for taking the time to create a detailed response here @DaniFoldi! I agree those are all great ideas.

If you don't mind, could you create separate issues for the icons you feel we are missing (we  have a standard process we follow for these)? It just makes it easier to track those rather than trying to keep updating this issue with our progress on different items.

@lucaburgio might also prefer separate issues for the circle / square variants, and the cloud / pharmacy icons. But I will leave that up to him to let you know his preference!


And for sure, I think we should let a 7.0.0 release "marinate" for a bit. That gives some more time to find inconsistencies and come up with an even more solid naming framework.


@lucaburgio - whenever you create that documentation on the naming conventions, I think it would be most beneficial to have that in a Markdown file at the root of the repository. Then it's visible for everyone to reference, and we can optionally accept PRs to make updates to that document.

**Comment by DaniFoldi** [comment]
Found another one:
`refresh-circular` -> `refresh-circle`
`reload-window` -> `window-refresh`

**Comment by sammarks** [comment]
Another one! While `cut` and `copy` exist as their own icons, paste is not `paste`, but `paste-clipboard`

**Comment by lucaburgio** [comment]
Thank you for spotting them 🙏 I'm already working on a branch to fix all these names while preparing the doc.
Is there a way to show you guys the branch without doing a pull request? @sammarks

**Comment by DaniFoldi** [comment]
Yup, here's a quick link: [feat-naming-convention](https://github.com/iconoir-icons/iconoir/tree/feat-naming-convention). It can also be found in the top-left corner. You also have the option to open a Draft PR, which GitHub prevents from getting merged before you mark it ready for review.

Would you like me to convert my comments into checklists and see which entries you've already done, or do you maintain a list somewhere?

**Comment by lucaburgio** [comment]
Sure, thank you!
I was using a list on Notion for simplicity, and it would be crazy to convert the whole list into checklist points now 😅, so I'll post the list here complete of what's done and what's planned.

Feel free to continue with a checklist 🙌  I'll use it to continue the work.

**🌱 DONE**

Other

`bookmark-empty` to `bookmark`
`divide-selection-1` to `split-area`
`cloud-book-alt` to `cloud-bookmark`
`privacy policy` to `privacy-policy` 
`save-floppy-disk` to `floppy-disk`
`load-action-floppy` to `floppy-disk-arrow-out`
`save-action-floppy` to `floppy-disk-arrow-in`
`main-opened` to `mail-open`
`pin-alt` to `map-pin`

No access

`card-issue` to `card-no-access`
`no-access-window` to `window-no-access`
`log-denied` to `log-no-access`

Warning

`folder-alert` to `folder-warning`
`wifi-issue` to `wifi-warning`
`laptop-issue` to `laptop-warning`
`tv-issue` to `tv-warning`
`domotic-issue` to `domotic-warning`
`headset-issue` to `headset-warning`
`shopping-bag-issue` to `shopping-bag-warning`

Lock

`card-locked` to `card-lock`
`locked-book` to `book-lock`
`locked-window` to `window-lock`
`lock-key` to `lock-square`

Circle

`coin` to `dollar-circle`
`hospital-sign` to `hospital-circle`
`info-empty` to `info-circle`
`refresh-circular` to `refresh-circle`

Shield

`card-security` to `card-shield`

Check

`check-window` to `window-check`
`voice-ok` to `voice-check`
`password-pass` to `password-check`
`clean-water` to `water-check`

Droplet

`gas-tank-drop` to `gas-tank-droplet`

Square

`settings-cloud` to `cloud-square`
`text-alt` to `text-square`
`cooling` to `cooling-square`
`selection` to `square-dashed`
`git-command` to `slash-square`
`divide-selection-2` to `split-square-dashed`
`fast-arrow-down-box` to `fast-arrow-down-square`
`fast-arrow-left-box` to `fast-arrow-left-square`
`fast-arrow-right-box` to `fast-arrow-right-square`
`fast-arrow-up-box` to `fast-arrow-up-square`
`heating` to `heating-square`
`carbon` to `c-square`
`fluorine` to `f-square`
`hydrogen` to `h-square`
`nitrogen` to `n-square`
`oxygen` to `o-square`
`x-coordinate` to `x-square`
`y-coordinate` to `y-square`
`z-coordinate` to `z-square`

Tag

`ar-symbol` to `ar-tag`
`vr-symbol` to `vr-tag`
`ip-address` to `ip-address-tag`
`closed-captions` to `closed-captions-tag`
`pharmacy-cross-square` to `pharmacy-cross-tag`
`down-round-arrow` to `arrow-down-tag`
`enlarge-round-arrow` to `arrow-enlarge-tag`
`left-round-arrow` to `arrow-left-tag`
`reduce-round-arrow` to `arrow-reduce-tag`
`right-round-arrow` to `arrow-right-tag`
`up-round-arrow` to `arrow-up-tag`

X Mark

`grid-remove` to `grid-xmark`
`remove-pin-alt` to `map-pin-xmark`
`remove-media-video` to `media-video-xmark`
`remove-media-image` to `media-image-xmark`
`remove-user` to `user-xmark`
`remove-square` to `xmark-square`
`multiple-pages-delete` to `multiple-pages-xmark`
`phone-delete` to `phone-xmark`
`delete-circle` to `xmark-circle`
`cancel` to `xmark`
`shield-cross` to `shield-xmark`
`map-issue` to `map-xmark`
`maps-arrow-issue` to `maps-arrow-xmark`
`cloud-error` to `cloud-xmark`
`bubble-error` to `bubble-xmark`
`chat-bubble-error` to `chat-bubble-xmark`
`wifi-error` to `wifi-xmark`
`fingerprint-error-circle` to `fingerprint-xmark-circle`
`voice-error` to `voice-xmark`
`password-error` to `password-xmark`
`shopping-code-error` to `shopping-code-xmark`
`error-window` to `window-xmark`
`drone-error` to `drone-xmark`
`ev-plug-error` to `ev-plug-xmark`
`web-window-close` to `web-window-xmark`

Minus

`remove-folder` to `folder-minus`
`remove-database-script` to `database-script-minus`
`remove-frame` to `frame-minus-in`
`ruler-remove` to `ruler-minus`
`remove-from-cart` to `cart-minus`
`remove-selection` to `minus-square-dashed`
`minus-pin-alt` to `map-pin-minus`

Green

`green-bus` to `bus-green`
`green-truck` to `truck-green`
`green-vehicle` to `vehicle-green`

Plus

`add-circle` to `plus-circle`
`add-square` to `plus-square`
`add-keyframe-alt` to `keyframe-plus-in`
`add-keyframe` to `keyframe-plus`
`add-keyframes` to `keyframes-plus`

**⚙️ TO DO / STILL FIGURING OUT WHICH RULE WOULD SOLVE**

If Plus

`add-circle` to `plus-circle`
`add-square` to `plus-square`
`add-keyframe-alt` to `keyframe-plus-in`
`add-keyframe` to `keyframe-plus`
`add-keyframes` to `keyframes-plus`
`mic-add` to `microphone-plus`
`chat-add` to `chat-plus-in`
`phone-add` to `phone-plus`
`add-database-script` to `database-script-plus`
`add-frame` to `frame-plus-in`
`add-lens` to `lens-plus`
`ruler-add` to `ruler-plus`
`add-folder` to `folder-plus`
`add-page` to `page-plus-in`
`multiple-pages-add` to `multiple-pages-plus`
`add-page-alt` to `page-plus`
`grid-add` to `grid-plus`
`music-double-note-add` to `music-double-note-plus`
`music-note-add` to `music-note-plus`
`playlist-add` to `playlist-plus`
`add-selection` to `plus-square-dashed`
`add-media-image` to `media-image-plus`
`add-media-video` to `media-video-plus`
`shield-add` to `shield-plus-in`
`add-hexagon` to `hexagon-plus`
`add-to-cart` to `cart-plus`
`shopping-bag-add` to `shopping-bag-plus`
`bin-add` to `bin-plus`
`add-user` to `user-plus`
`add-pin-alt` to `map-pin-plus`

Minus (or remove/issue/no-access/delete/error?)

Minus

`key-alt-minus`

Currently, with the X symbol:

`key-alt-remove` to ?
`db-error` to ?

To define or to re-consider:

`3d-add-hole`
`search-font`
`voice-phone`
`bin-minus`
`eye-off`
`network-alt`? `network-reverse`

**Comment by DaniFoldi** [comment]
Wow, that's a rather impressive list!

Actually, a draft PR might help find further items, if Pages does a deploy and we get a preview URL to see the updated names in their place 😅

**Comment by lucaburgio** [comment]
Sure! Here is the [PR](https://github.com/iconoir-icons/iconoir/pull/276), updated with the last commits.
