### ISSUE TITLE
[Bug] IconoirContext in server components has no effect in next.js v13.2.1

### ISSUE THREAD

**Issue by AlphaByte-RedTeam** [iconoir-icons/iconoir#253]
## Problem
It seems that IconoirProvider doesn't work with next.js server components. So, in the new version of [Next.js v13.2](https://nextjs.org/blog/next-13-2#built-in-seo-support-with-new-metadata-api) , it brings the new feature of Metadata API to replace `head.js`.  In order to use the metadata API, you should not use the API inside client components.

If I try to use IconoirProvider alongside with Metadata API, the IconoirProvider will throw a warning that it has no effect on server components.

## Prerequisites

* Version: Iconoir 6.3.0
* Are you running from source/main: yes
* Are you using a released build: yes
* Operating system: Windows 11

## Step to reproduce

1. Create a next.js 13 project with typescript and enable experimental app directory feature
2. Install iconoir react
3. Import `IconoirProvider` in `layout.tsx`
4. Wrap the `{children}` in `<head>` tag with the `<IconoirProvider />`
```tsx
<body>
	<IconoirProvider
		iconProps={{
			strokeWidth: 1,
			width: "1.5rem",
			height: "1.5rem",
		}}
	>
		{children}
	</IconoirProvider>
</body>
```
5. Run your development server

### Actual behavior
Running the development server will throw a warning that tells it has no effect.

## Any message or error
```
Using IconoirContext in server components has no effect, because server components do not support React Context. If you would like to use IconoirContext, add 'use client' to the top of your component.
```

## Additional info or screenshots
- Using experimental app directory feature
- Using turbopack
- Using next.js latest version
- Using yarn package manager

![image](https://user-images.githubusercontent.com/49155225/221326628-81d050cc-49e2-457a-9bfd-92db205c6bc9.png)

**Comment by sammarks** [comment]
React Context isn't supported inside server components, and IconoirProvider works by using React Context to store common properties to pass to the icons as you use them.

Since context isn't supported inside Server Components, you will have to find a client component suitable to place the IconoirProvider in.
