### ISSUE TITLE
Icons in CDN do not match icons on Homepage

### ISSUE THREAD

**Issue by nicholasareed** [iconoir-icons/iconoir#255]
## Prerequisites

* Version: 6.3.0
* Are you running from source/main: yes, via CDN link in documentation 
* Are you using a released build: see above
* Operating system: osx 

## Step to reproduce

1. Use the CDN link and `<i class="iconoir-network-alt"></i>` 
2. Visit homepage and view the `network-alt` icon to see differences (the CDN version is missing the little boxes at the ends of each) 

You can also compare website download against the SVG from the CDN link: https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css 

CDN Version: 
```
<svg stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><rect rx="0.6" transform="matrix(1 0 0 -1 3 22)" stroke="currentColor" stroke-width="1.5"/><rect rx="0.6" transform="matrix(1 0 0 -1 8.5 7)" stroke="currentColor" stroke-width="1.5"/><rect rx="0.6" transform="matrix(1 0 0 -1 14 22)" stroke="currentColor" stroke-width="1.5"/><path d="M6.5 17V13.5C6.5 12.3954 7.39543 11.5 8.5 11.5H15.5C16.6046 11.5 17.5 12.3954 17.5 13.5V17" stroke="currentColor" stroke-width="1.5"/><path d="M12 11.5V7" stroke="currentColor" stroke-width="1.5"/></svg>
```

SVG from homepage: 
```
<svg width="24px" height="24px" stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="#000000"><rect width="7" height="5" rx="0.6" transform="matrix(1 0 0 -1 3 22)" stroke="#000000" stroke-width="1.5"></rect><rect width="7" height="5" rx="0.6" transform="matrix(1 0 0 -1 8.5 7)" stroke="#000000" stroke-width="1.5"></rect><rect width="7" height="5" rx="0.6" transform="matrix(1 0 0 -1 14 22)" stroke="#000000" stroke-width="1.5"></rect><path d="M6.5 17v-3.5a2 2 0 012-2h7a2 2 0 012 2V17M12 11.5V7" stroke="#000000" stroke-width="1.5"></path></svg>
```

### Actual behavior

They don't match.

**Comment by sammarks** [comment]
Thanks for reporting! I'll take a look at this.

![image](https://user-images.githubusercontent.com/424093/222485124-a5c24625-1f1a-4796-8179-a7064b2ab627.png)

It looks like this is because the `rect` elements are being changed to use `transform()` which I doubt is supported in the mask approach, so it's not getting the size of them correct.

I think this is just a matter of updating the svgo options for the CSS file to not use the transform, and instead keep the original width + height (which will increase the size of the CSS file, unfortunately).

**Comment by Diebolik** [comment]
Hello. 

I found an another icon problem.: sound-off

Version: v6.4.0

CDN Version:
`<svg viewBox="0 0 24 24" stroke-width="1.5" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_3173_16686)"><path d="M18 14L20.0005 12M22 10L20.0005 12M20.0005 12L18 10M20.0005 12L22 14" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/><path d="M2 13.8571V10.1429C2 9.03829 2.89543 8.14286 4 8.14286H6.9C7.09569 8.14286 7.28708 8.08544 7.45046 7.97772L13.4495 4.02228C14.1144 3.5839 15 4.06075 15 4.85714V19.1429C15 19.9392 14.1144 20.4161 13.4495 19.9777L7.45046 16.0223C7.28708 15.9146 7.09569 15.8571 6.9 15.8571H4C2.89543 15.8571 2 14.9617 2 13.8571Z" stroke="currentColor"/></g><defs><clipPath id="clip0_3173_16686"><rect fill="white"/></clipPath></defs></svg>`

SVG from homepage:
`<svg width="24px" height="24px" viewBox="0 0 24 24" stroke-width="1.5" fill="none" xmlns="http://www.w3.org/2000/svg" color="#000000"><g clip-path="url(#sound-off_svg__clip0_3173_16686)" stroke="#000000" stroke-width="1.5"><path d="M18 14l2-2m2-2l-2 2m0 0l-2-2m2 2l2 2" stroke-linecap="round" stroke-linejoin="round"></path><path d="M2 13.857v-3.714a2 2 0 012-2h2.9a1 1 0 00.55-.165l6-3.956a1 1 0 011.55.835v14.286a1 1 0 01-1.55.835l-6-3.956a1 1 0 00-.55-.165H4a2 2 0 01-2-2z"></path></g><defs><clipPath id="sound-off_svg__clip0_3173_16686"><path fill="#fff" d="M0 0h24v24H0z"></path></clipPath></defs></svg>`

**Comment by Diebolik** [comment]
Hello. 

I found an another icon problem.: privacy policy

Version: v6.4.0

The name of this icon in the CDN css file is not workink: iconoir-privacy policy

**Comment by f11xter** [comment]
Similarly, most of the mic icons are missing the actual microphone part.

Affects `mic`, `mic-add`, `mic-check`, `mic-remove`, `mic-speaking`, `mic-warning`.

It looks like the `rect` element width and height are missing here too, though the other paths also differ.
