### ISSUE TITLE
[ICON] "Three dots" that are vertical and another that is horizontal

### ISSUE THREAD

**Issue by mypalvikram** [iconoir-icons/iconoir#260]
## Icon Request

Not sure about the name but:

* Icon name: "Menu action"? "Menu Popout"?
* Use case: Usually on a mobile device when you see these three dots it means there is a popout menu action associated with it.
* Screenshots of similar icons: 

<img width="99" alt="Screenshot 2023-03-09 at 9 28 47 AM" src="https://user-images.githubusercontent.com/6226652/224107624-3f2799f1-798d-4d88-80ad-d44acbfe9a68.png">

<img width="166" alt="Screenshot 2023-03-09 at 9 30 17 AM" src="https://user-images.githubusercontent.com/6226652/224107974-8fe9e912-076b-42e2-b814-aca7fc60e66e.png">

**Comment by lucaburgio** [comment]
You can find them looking for the keyword `more`. I'll definitely add more keywords for them.

**Comment by mypalvikram** [comment]
> You can find them looking for the keyword `more`. I'll definitely add more keywords for them.

Oops, I missed that. Thanks!

Would it be possible to increase the size of the dots? Manually setting them about 10px higher to look consistent.

24 x 24

<img width="473" alt="Screenshot 2023-03-11 at 12 59 38 PM" src="https://user-images.githubusercontent.com/6226652/224511380-d8a25b0a-5e8a-4593-949f-45b35ddf7740.png">

**Comment by lucaburgio** [comment]
I'm going to check that. First, thank you for spotting these icons! It's really helpful in improving the visual consistency of some icons years old that I probably missed optimizing.

**Comment by lucaburgio** [comment]
Could you be more specific on whats the issue with the dots?
As you can see from the image attached, the current visual size seems consistent to me.
(Green is your screenshot, Yellow is Iconoir with 1.5px stroke, Red is Iconoir with 2px stroke).

<img width="746" alt="image" src="https://user-images.githubusercontent.com/6526461/224572841-23b988b6-2f7a-4caa-9817-fcbcd87520ca.png">

Apart from this, I will optimize them anyway, as we will change the visual dimension of the arrows, and these should be optimized accordingly.

Let me know if what I showed to you makes sense.
Thank you!

**Comment by mypalvikram** [comment]
> Could you be more specific on whats the issue with the dots? As you can see from the image attached, the current visual size seems consistent to me. (Green is your screenshot, Yellow is Iconoir with 1.5px stroke, Red is Iconoir with 2px stroke).
> 
> <img alt="image" width="746" src="https://user-images.githubusercontent.com/6526461/224572841-23b988b6-2f7a-4caa-9817-fcbcd87520ca.png">
> 
> Apart from this, I will optimize them anyway, as we will change the visual dimension of the arrows, and these should be optimized accordingly.
> 
> Let me know if what I showed to you makes sense. Thank you!

Thank you for taking the time to send that over! Yeah definitely makes sense, while testing my application someone pointed out to me that the dots look small and they almost didn't see them. Compared to the arrow on the left which is much easier to see and has the same dimensions.
