### ISSUE TITLE
[FEAT] Better fill on the "User" icon and others

### ISSUE THREAD

**Issue by mypalvikram** [iconoir-icons/iconoir#277]
The first example is the "User" icon. When setting a fill option it doesn't fill completely on the bottom.

No fill:
<img width="52" alt="Screenshot 2023-03-28 at 4 31 23 PM" src="https://user-images.githubusercontent.com/6226652/228389624-639443cf-1e02-4291-aa47-febb6ca05d1e.png">

Fill:
<img width="44" alt="Screenshot 2023-03-28 at 4 31 38 PM" src="https://user-images.githubusercontent.com/6226652/228389648-f51b9804-022d-4b11-a60e-f4353ae0d2e3.png">

The other ones that I've tested is the "Calendar"

No fill:
<img width="61" alt="Screenshot 2023-03-28 at 4 32 08 PM" src="https://user-images.githubusercontent.com/6226652/228389700-58cdbcb4-4a10-41e0-927e-a5d57fbc2cb9.png">

Fill:
<img width="51" alt="Screenshot 2023-03-28 at 4 32 26 PM" src="https://user-images.githubusercontent.com/6226652/228389722-022f96a8-8a5a-49e1-b517-d8660c67d59d.png">

**Comment by sammarks** [comment]
I'll defer to @lucaburgio for his opinion on filled icons, but you may want to see our other conversation on this here: https://github.com/iconoir-icons/iconoir/issues/257

**Comment by lucaburgio** [comment]
@mypalvikram The `fill` prop does not work well with outline icons, as they're meant to stay as is. I'm working on a `solid` version of Iconoir to fulfill this need ⚙️  Stay tuned!

**Comment by its-monotype** [comment]
> @mypalvikram The `fill` prop does not work well with outline icons, as they're meant to stay as is. I'm working on a `solid` version of Iconoir to fulfill this need ⚙️  Stay tuned!

Look forward to. It will be very helpful.

**Comment by lucaburgio** [comment]
@visualsitemaps @its-monotype I will need more time to release the solid icons, but everything is planned already 🙌

**Comment by plaskevich** [comment]
@lucaburgio any updates on the solid version of icons?
