### ISSUE TITLE
Documentation on website has the wrong urls

### ISSUE THREAD

**Issue by Cadiducho** [iconoir-icons/iconoir#279]
Hi, I was browsering your docs on the website https://iconoir.com/docs/introduction and I noticed some of the links that are broken: 
![image](https://user-images.githubusercontent.com/3594924/229476496-99d90c10-06b8-43ee-b78a-97f596163970.png)

I think this is because the website is displaying the Readme of the repo, which has relative URLs instead of absolute ones (https://github.com/iconoir-icons/iconoir/blob/main/README.md?plain=1#L50). 
While these relative URLs work on GitHub inside the repo, they do not exist on the deployed website (https://iconoir.com/docs/packages/iconoir-react-native, for example).

I'm not sure how you deploy the website, so this is just an idea and not a pull request. :sweat_smile:

**Comment by lucaburgio** [comment]
Thank you! I'm going to fix it soon ⚙️

**Comment by lucaburgio** [comment]
Solved in [a9f4aba](https://github.com/iconoir-icons/iconoir/commit/a9f4aba656cd1636056c0db9a69d60cb7733adc5)
