### ISSUE TITLE
Downloading from /icons has different SVG's than downloading from Web.

### ISSUE THREAD

**Issue by mkaulfers** [iconoir-icons/iconoir#284]
## Prerequisites

* Version: Latest (N/A)
* Are you running from source/main: Yes (N/A)
* Are you using a released build: N/A
* Operating system: N/A

## Step to reproduce

- Download any Icon from the [raw.github endpoint. ](https://raw.githubusercontent.com/iconoir-icons/iconoir/main/icons/1st-medal.svg)

- Import that icon into XCode manually. Notice that the SVG is not visible/usable. I also attempted to set the rendering mode and toyed around with any of the `Contents.JSON` options however nothing will make them usable. 

- Download any Icon from www.iconoir.com and then import into XCode, works as expected. 

This Script, is currently broken, but it's what made the problem obvious. The intention here is to have all of the icons downloaded and then added as an asset to a project, but for obvious reasons it's not working. The script is NOT the problem, I already tested it without using the script, by manually performing the steps that the script does, and the issue still persists. 

https://gist.github.com/mkaulfers/2200dcfa76bad800823eca0e975103f6

## Additional info or screenshots

- Is there any form of processing happening on the web side with these icons? If there is, can we modify that to have some pre-processing Workflow to process it before adding to the repo, or show what that processing action is so that I can update my script to handle it. 

- [StackOverflow Question](https://stackoverflow.com/questions/76016433/what-svg-tags-are-required-for-xcode-swift-support)

![Screenshot 2023-04-18 at 11 20 50 AM](https://user-images.githubusercontent.com/42121989/232841173-aa328481-0e97-4b6e-84c8-39cf1ff013e4.png)

![Screenshot 2023-04-18 at 11 21 18 AM](https://user-images.githubusercontent.com/42121989/232841286-7b92fcb4-33cc-44ac-93fb-55b5d4b6a527.png)

**Comment by paescuj** [comment]
Difference is that the files downloaded from the website contain an XML declaration (see https://oreillymedia.github.io/Using_SVG/extras/ch01-XML.html): `<?xml version="1.0" encoding="UTF-8"?>`

It seems like XCode or the tools you rely on in your scripts require this XML declaration in order to interpret the files correctly. So you might want to add this XML declaration to the files inside your script.

**Comment by mkaulfers** [comment]
@paescuj No that doesn't seem to be the cause of it. 

```XML
<?xml version="1.0" encoding="UTF-8"?>
<svg width="24" height="24" stroke-width="1.5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14.2718 10.445L18 2M9.31612 10.6323L5 2M12.7615 10.0479L8.835 2M14.36 2L13.32 4.5M6 16C6 19.3137 8.68629 22 12 22C15.3137 22 18 19.3137 18 16C18 12.6863 15.3137 10 12 10C8.68629 10 6 12.6863 6 16Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M10.5 15L12.5 13.5V18.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by paescuj** [comment]
Oh right, also `currentColor` gets replaced by the selected color on the website which is usually `#000000`:
https://github.com/iconoir-icons/iconoir/blob/7adad51d3d9bbc7964d70a3891d6d4c04b6ddacd/iconoir.com/components/Icon.tsx#L16-L22

**Comment by mkaulfers** [comment]
@paescuj so the issue wasn't the XML tags, it is actually the current-color and stroke width tags that ended up fixing it. Good callout, however shouldn't we have these set as a default value in the repository, and only change it as needed when downloading? I fail to see why we'd keep them without those values being set. Thanks!

**Comment by paescuj** [comment]
No, I don't think so. That's actually inteded so the color isn't hard-coded and adapts to the current color in the browser.
