### ISSUE TITLE
[FEAT] : Footer button

### ISSUE THREAD

**Issue by elite16op** [iconoir-icons/iconoir#287]
**Is your feature request related to a problem? Please describe.**
What if a person has to check your footer section from the home page of your website only, it get's very tedious to scroll to the bottom of the page due to the huge number of icons.

**Describe the solution you'd like**
It would be great if we have a button to directly jump to the footer section of your website.

**Describe alternatives you've considered**
Alternate changes could be that we should have icons categories only show on home page and when user select one category the icons get maximize, this way our footer section can be accessible faster.

**Comment by sammarks** [comment]
What benefit is it to make sure to get to the footer section faster? Most of the relevant links inside the footer can be accessed via the navigation at the top of the page and the sub-navigation within.

As another note, if you need to get to the footer faster you can hit the cmd + down arrow button a few times (or I believe the end key), and that'll take you to the footer of the page.
