### ISSUE TITLE
[FEAT] TTF Format

### ISSUE THREAD

**Issue by itmanyong** [iconoir-icons/iconoir#289]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I hope to provide icon export in ttf font format

**Describe alternatives you've considered**
I haven't thought of it yet

**Additional context**
No

**Comment by CryptoCrocodile** [comment]
Is the icon pack available as a OTF or TTF? According to the website, it is - but I could not find any traces of it.

**Comment by paescuj** [comment]
> Is the icon pack available as a OTF or TTF? According to the website, it is - but I could not find any traces of it.

No, it isn't. What on the website gave this impression?

**Comment by CryptoCrocodile** [comment]
On the website it says:

> A high-quality selection of free icons. No premium options or sign-ups. Your new alternative to Noun Project, Flaticon, and all Figma resources. Available in SVG, **Font**, React, React Native, Flutter, Figma and Framer.

**Comment by lucaburgio** [comment]
We supported it in the past but the process wasn't automated.
I'll remove the word from that copy for now.

Thank you!
