### ISSUE TITLE
[ICON] Git logomark

### ISSUE THREAD

**Issue by evur** [iconoir-icons/iconoir#299]
## Icon Request

See <https://git-scm.com/downloads/logos>

* Icon name: Git (logomark)
* Use case: Representation of Git
* Screenshots of similar icons:

![](https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/299">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/299/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/299/pledge.svg">
</picture>
</a>

**Comment by lucaburgio** [comment]
Released.
