### ISSUE TITLE
Unable to find directory entry in pubspec.yaml from cache

### ISSUE THREAD

**Issue by manoelsrs** [iconoir-icons/iconoir#309]
I'm facing this error: `Error: unable to find directory entry in pubspec.yaml: /*/**/.pub-cache/hosted/pub.dev/iconoir_flutter-6.8.0/../../icons/` on version 6.8.0.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E261 darwin-arm64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

Could someone please help me?

**Comment by pomarec** [comment]
Any workaround ?

**Comment by pzehle** [comment]
Nothing. No answer, no updates, nothing....

**Comment by Watss** [comment]
In case it helps anyone, this happens because in the .yml assets, there are some that are not being found, such as a non-existent image, etc.

I don't know why it only shows the iconoir error
