### ISSUE TITLE
[ИКОНКА] BEER LOGO

### ISSUE THREAD

**Issue by not5a5villain555** [iconoir-icons/iconoir#315]
## Icon Request

* Icon name:
* Use case:
* Screenshots of similar icons:

**Comment by paescuj** [comment]
Could you provide an image of a similar icon to get an idea how you imagine it to be implemented?

**Comment by paescuj** [comment]
Closing this for now as it's missing information. See also https://github.com/iconoir-icons/iconoir/blob/main/CONTRIBUTING.md#icon-requests.
Thank you for your understanding!
