### ISSUE TITLE
Set stroke width when using iconoir css implementation. 

### ISSUE THREAD

**Issue by jonadeline** [iconoir-icons/iconoir#317]
Hi, 
Is there any way to set the stroke width to a custom value when using the css implementation?

**Comment by sammarks** [comment]
Unfortunately, not currently since the stroke-width is hard-coded in the CSS SVG mask. [I'm not entirely sure it's possible,](https://stackoverflow.com/questions/42330075/is-there-a-way-to-interpolate-css-variables-with-url) either, to include CSS variables inside a mask.

**Comment by jonadeline** [comment]
Ok it's what I thought. Thank you
