### ISSUE TITLE
Problems with imports in the Flutter package

### ISSUE THREAD

**Issue by pzehle** [iconoir-icons/iconoir#318]
## Prerequisites

* Version: 6.9.0
* Are you running from source/main: yes
* Are you using a released build: yes
* Operating system: MacOS

## Step to reproduce

Just install the package in a flutter project and try to put a Text() widget.

### Actual behavior

```
The name 'Text' is defined in the libraries 'package:flutter/src/widgets/text.dart' and 'package:iconoir_flutter/text.dart (via package:iconoir_flutter/iconoir_flutter.dart)'.
```

## Any message or error

Above.

## Additional info or screenshots

No

**Comment by sammarks** [comment]
Since both packages have a Text widget, you'll need to use prefixes in order to avoid this error:

```dart
import 'package:flutter/src/widgets/text.dart';
import 'package:iconoir_flutter/iconoir_flutter.dart' as iconoir;

// Now, you can refer to the 'Text' in the flutter library as just 'Text'
// and the 'Text' in the iconoir_flutter library as 'iconoir.Text'.
```

Then when you want to use 'Text' widget from Flutter, you just use 'Text', and when you want to use 'Text' from Iconoir, you use 'iconoir.Text'. 

For instance:

```dart
Text('Hello from Flutter');

iconoir.Text('Hello from Iconoir');
```

**Comment by pzehle** [comment]
Thank you.
