### ISSUE TITLE
Request for Adding New Icons to an Icon Library Supporting Svelte and SvelteKit

### ISSUE THREAD

**Issue by newkincode** [iconoir-icons/iconoir#331]
**Is your feature request related to a problem? Please describe.**
As a developer using Svelte and SvelteKit, I often encounter situations where I need additional icons beyond the ones provided by the existing icon library. Unfortunately, the current icon library I'm using does not support the specific icons I require, leading to frustration.

**Describe the solution you'd like**
I kindly request the icon library supporting Svelte and SvelteKit to add new icons. Ideally, these icons should be versatile and usable across various themes, allowing developers to utilize them in different projects.

**Describe alternatives you've considered**
I have considered manually modifying the icon library to add the desired icons, but this approach is cumbersome and may lead to maintenance challenges. Having a feature where library developers can add new icons would be highly beneficial.

**Additional context**
Icons play a crucial role in web applications and mobile app development. Although the current library is helpful, having access to a wider range of icons would significantly streamline the development process. Thank you.

**Comment by sammarks** [comment]
Please specify the icons you're looking for, following the instructions in the icon request template.
