### ISSUE TITLE
Framer missing latest icons

### ISSUE THREAD

**Issue by addisonjames** [iconoir-icons/iconoir#344]
Hey, sent a tweet to you about this, but then found the git. Wasn't sure where to file this under, but I'm trying to release a template using Iconoir and the missing icons are holding me back. TIA :) 

## Prerequisites

* Version: Framer 2023.15.1
* Are you running from source/main: Framer
* Are you using a released build: Yes
* Operating system: macOS 13.5 (22G74)

## Step to reproduce

Insert Framer component for Iconoir

## Any message or error

None- just missing many icons. Tried to type name in manually but doesn't work.

## Additional info or screenshots

* Screenshots

**Comment by lucaburgio** [comment]
They need to pull from Iconoir in order to update the library in the editor. I'll ping them as soon as I can.

**Comment by addisonjames** [comment]
Thanks!

**Comment by addisonjames** [comment]
v7 looks great! Still wishing Framer would update 😩

**Comment by addisonjames** [comment]
Can't tell you how many people in Framer's support forums reply to my post asking about this. Still hoping we can get them to update one day!
