### ISSUE TITLE
[FEAT]

### ISSUE THREAD

**Issue by hitaboy** [iconoir-icons/iconoir#348]
**Is your feature request related to a problem? Please describe.**
I want to contribute creating the svelte library for iconoir

**Describe the solution you'd like**
Learn how you have build the react library and try to propose a similar approach adapted to svelte js.
The challenge is to have the same props exposed as react version.

**Describe alternatives you've considered**
I have not considered any

**Additional context**

**Comment by paescuj** [comment]
Hey 👋 Pull requests are always welcome! See also https://github.com/iconoir-icons/iconoir/blob/main/CONTRIBUTING.md to learn more about contributing. However, I'm going to close this issue as the addition of a Svelte library is already tracked in #302.

**Comment by indaco** [comment]
@hitaboy you could help bringing https://github.com/indaco/svelte-iconoir to this org. 

@lucaburgio  reached me already to work on that but for limited time on my own it is still there as independent package

Please, share your thoughts
