### ISSUE TITLE
[ICON] VS Code

### ISSUE THREAD

**Issue by Carmem1629** [iconoir-icons/iconoir#361]
## Icon Request

* Icon name: vscode
* Use case:
* Screenshots of similar icons:

**Comment by paescuj** [comment]
Please provide an use case and screenshot.

**Comment by paescuj** [comment]
Please fill out the report completely. See also https://github.com/iconoir-icons/iconoir/blob/main/CONTRIBUTING.md#icon-requests.
Closing this for now, but you're welcome to open up a new filled-out issue for this request. Thank you for your understanding!
