### ISSUE TITLE
[Question] Privacy policy icon name

### ISSUE THREAD

**Issue by indaco** [iconoir-icons/iconoir#371]
Looks like the only one without a dash char in the name

![image](https://github.com/iconoir-icons/iconoir/assets/13519/dbeeffb7-65f1-46c8-ae0a-0e0bb2fb27e6)

Is it a mistake?
Thanks

**Comment by lucaburgio** [comment]
Hi @indaco,
This has been fixed in `7.0.0`.

`7.0.0` will be released asap 🙌
