### ISSUE TITLE
Bad stroke-width for airplane-rotation icon

### ISSUE THREAD

**Issue by Silbad** [iconoir-icons/iconoir#373]
Hi,

I found two paths with stroke-width values: 1.49671. Is this normal? Or a small rounding error?
I've checked that none of your paths contain stroke-width.

Thanks,

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/373">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/373/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/373/pledge.svg">
</picture>
</a>

**Comment by lucaburgio** [comment]
👋 An issue. Will fix it soon.
