### ISSUE TITLE
[ICON] Polar.sh

### ISSUE THREAD

**Issue by birkjernstrom** [iconoir-icons/iconoir#381]
## Icon Request

* Icon name: Polar
* Use case: Open source funding with Polar
* Screenshots of similar icons:

![image](https://github.com/iconoir-icons/iconoir/assets/281715/1fb623bf-a8e1-49b6-a5a9-8788b491a19e)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/381">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/381/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/381/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Just funded on behalf of Polar. Polar funding via Polar to see a delicious Polar icon in the beautiful iconoir set 😍

**Comment by paescuj** [comment]
> Just funded on behalf of Polar. [...]

Wow, let me already thank you on behalf of Iconoir! ❤️ This is highly appreciated!

I didn't know about Polar until @lucaburgio adopted it on this repository, but I immediately fall in love with the concept and great & thoughtful design of the platform!

> [...] Polar funding via Polar to see a delicious Polar icon in the beautiful iconoir set 😍

🌀😁

**Comment by birkjernstrom** [comment]
Thank you so much for the super kind words of encouragement @paescuj – we really appreciate it ♥️

Also, I can't believe that TIL about the 🌀 emoji. It's absolutely brilliant and now I'll use it everywhere for Polar 😅 That is everywhere that doesn't use iconoir once our icon comes out there 😉
