### ISSUE TITLE
[ICON]

### ISSUE THREAD

**Issue by rzlartnto** [iconoir-icons/iconoir#384]
## Icon Request

* Icon name: Iconoir
* Use case: for personal use
* Screenshots of similar icons: i dont have

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/384">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/384/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/384/pledge.svg">
</picture>
</a>

**Comment by paescuj** [comment]
There's already an Iconoir icon: https://github.com/iconoir-icons/iconoir/blob/main/icons/regular/iconoir.svg
