### ISSUE TITLE
[BUG] The Plus icon is the wrong size

### ISSUE THREAD

**Issue by AlreNux** [iconoir-icons/iconoir#386]
## Prerequisites

* Version: 7.1.0
* Are you running from source/main:
* Are you using a released build:
* Operating system:

### Actual behavior

*When starting a local dev server, the icon is not rendered the way it should be (compared to other icons). I set it to 24px (for width and height) in the tsx component. The output is rendered with 24px size "svg" tag and 12 px "path" tag. The "path" tag is dynamic and is exactly half the size of the "svg" tag. The bug is that "path" doesn't stretch to the full width of the container.*

## Additional info or screenshots

`   
<Plus
      height={24}
      strokeWidth={2}
      width={24}
 />
 `

![image](https://github.com/iconoir-icons/iconoir/assets/81815016/bf4ddc9f-bcf3-4d0e-9b11-a615a5613f3f)
![image](https://github.com/iconoir-icons/iconoir/assets/81815016/d317b979-a99a-4170-af98-f808c8734527)
![image](https://github.com/iconoir-icons/iconoir/assets/81815016/58c2c1c1-836a-4b5d-8309-b14b2b0de0a6)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/386">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/386/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/386/pledge.svg">
</picture>
</a>

**Comment by SpeedySH** [comment]
Same Problem. Some icons have a small path and an extra free space in the "container"
