### ISSUE TITLE
Can't use partially transparent color with headset-help icon

### ISSUE THREAD

**Issue by tzachov** [iconoir-icons/iconoir#387]
## Prerequisites

* Version: 6.11.0
* Are you running from source/main: No
* Are you using a released build: Yes
* Operating system: MacOS

## Step to reproduce
Add HeadsetHelp icon to a page
Set its fill color to a non-solid color (e.g. `#00000050`)

### Actual behavior
See screenshot

## Additional info or screenshots

* Screenshots
<img width="193" alt="image" src="https://github.com/iconoir-icons/iconoir/assets/11992871/7f3025ba-fe63-4628-8a2d-2bc2838feb0b">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/387">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/387/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/387/pledge.svg">
</picture>
</a>

**Comment by lucaburgio** [comment]
Hi Tzach,
thank you for the feedback.

Exploded paths in some icons cause this. These paths are useful to make some complex icons compatible with SVG import in some software.

I'm working on fixing this soon. You'll see the change in the coming releases ⚙️

**Comment by lucaburgio** [comment]
There are some compromises to make between SVG standards and scalability. Initially these paths were truncated to make the icon more compatible with exports and some design tools (this applies basically to every library or SVGs, not Iconoir only).
I'm currently working on finding the optimal solution.
Meanwhile, I released the fix for this icon in v7.2.0 ✅
