### ISSUE TITLE
[ICON] Gear

### ISSUE THREAD

**Issue by mateusz-uzz** [iconoir-icons/iconoir#392]
## Icon Request

* Icon name: gear / settings
* Use case: Used to indicate a settings page or link

* Screenshots of similar icons:
![image](https://github.com/iconoir-icons/iconoir/assets/80593764/c2ccbea0-f53e-49ad-86d6-c7b64a9dbc29)
The windows 11 settings icon

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/392">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/392/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/392/pledge.svg">
</picture>
</a>

**Comment by DaniFoldi** [comment]
Hi @mateusz-uzz :wave:

Thanks for creating this icon request. I believe Iconoir already contains such an icon, please look for `settings`. If you're looking for something else, feel free to reopen this issue.
