### ISSUE TITLE
[React library] Add custom index for svgr

### ISSUE THREAD

**Issue by PianoManDanDan** [iconoir-icons/iconoir#40]
As discussed in [this PR](https://github.com/lucaburgio/iconoir/pull/35), we want to have a custom index file for svgr to use for generating nicer types that can be used in Typescript.

**Describe the solution you'd like to have**
A custom `index.js` file that svgr uses to generate the files in `~/packages/iconoir-react/src/`.

**Comment by paescuj** [comment]
Thanks @PianoManDanDan! Just adding this quote as a quick reference:
> Note: While the automatically generated types definition aren't ideal, it does work for now. I think it should be changed to something similar as [the current definition](https://github.com/lucaburgio/iconoir/blob/18671eed7e425ab043233e596f90581eae193557/packages/iconoir-react/src/index.d.ts) - this would mean we have to create a [custom index.js template for svgr](https://react-svgr.com/docs/options/#indexjs-template).
