### ISSUE TITLE
Tools icon does not scale correctly

### ISSUE THREAD

**Issue by nabelekt** [iconoir-icons/iconoir#407]
## Prerequisites

* Version: 7.4.0
* Are you running from source/main: Copied from Figma community
* Are you using a released build:
* Operating system:

## Step to reproduce

Insert `tools` icon and drag handles to scale.

### Actual behavior

Breaks apart. Only part of it scales

## Additional info or screenshots

![image](https://github.com/iconoir-icons/iconoir/assets/7028403/ef019795-a101-4feb-a8a8-b2a4e679a3a6)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/407">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/407/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/407/pledge.svg">
</picture>
</a>

**Comment by nabelekt** [comment]
Same with the `wrench`.

**Comment by lucaburgio** [comment]
Solved in `v7.6.0`.
