### ISSUE TITLE
Screwdriver-Wrench

### ISSUE THREAD

**Issue by PrajwalSh0206** [iconoir-icons/iconoir#409]
## Icon Request

* Icon name: Screwdriver-Wrench
* Use case: This icon indicates that repairs are underway.
* Screenshots of similar icons:
![Screenshot 2024-02-27 074346](https://github.com/iconoir-icons/iconoir/assets/39595250/1131f6eb-0f54-41af-8fc8-272b0bc6067d)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/409">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/409/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/409/pledge.svg">
</picture>
</a>

**Comment by Revenciel** [comment]
This icon is already in the library under the name "tools"

**Comment by paescuj** [comment]
Thanks @Revenciel! Closing for now as `tools` seems to be exactly what @PrajwalSh0206 is looking for 👍
