### ISSUE TITLE
[ICON] Check square

### ISSUE THREAD

**Issue by ceopaludetto** [iconoir-icons/iconoir#420]
## Icon Request

* Icon name:  Check Square
* Use case: To create multiple selects/checkboxes
* Screenshots of similar icons:
<img width="244" alt="Screenshot 2024-03-25 at 19 17 14" src="https://github.com/iconoir-icons/iconoir/assets/30508218/8e78670a-39f8-477a-a99b-295f9cffa276">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/420">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/420/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/420/pledge.svg">
</picture>
</a>

**Comment by lucaburgio** [comment]
Live
