### ISSUE TITLE
[FEAT] Website dark theme

### ISSUE THREAD

**Issue by KaKi87** [iconoir-icons/iconoir#425]
**Is your feature request related to a problem? Please describe.**
The website only features a light theme.

**Describe the solution you'd like**
The website would also feature a dark theme.

**Describe alternatives you've considered**
None

**Additional context**
None

---

Thanks

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/425">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/425/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/425/pledge.svg">
</picture>
</a>

**Comment by lucaburgio** [comment]
Currently not a priority.

**Comment by KaKi87** [comment]
Why not letting the issue remain open in backlog then ?
