### ISSUE TITLE
Verified [ICON]

### ISSUE THREAD

**Issue by liracinai** [iconoir-icons/iconoir#426]
## Icon Request

* Icon name: Verified
* Use case: Verified profile for an app
* Screenshots of similar icons: 
![](https://static.vecteezy.com/system/resources/previews/026/306/102/original/verified-icon-verify-tick-okay-ok-check-checked-approve-approval-right-vote-black-white-round-circle-sign-symbol-artwork-graphic-clipart-eps-vector.jpg)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/426">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/426/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/426/pledge.svg">
</picture>
</a>

**Comment by paescuj** [comment]
Hey, thanks for the request!
This actually already exists: `check-circle-solid`
