### ISSUE TITLE
Adding support for Penpot

### ISSUE THREAD

**Issue by N4taaa** [iconoir-icons/iconoir#436]
**Is your feature request related to a problem? Please describe.**
Penpot is a FOSS, self-hostable alternative to Figma, which is, actually, quite powerful. [https://github.com/penpot/penpot](https://github.com/penpot/penpot). I'd love to have an Iconoir library for this platform, as it is my go-to for design and code collaboration, and it shares a lot of the same goals with the Iconoir mindset!

**Describe the solution you'd like**
Previously explained.

**Describe alternatives you've considered**
It is already possible to import SVG, but it would be beneficial for lazy people like myself :)

**Additional context**
[This](https://penpot.app/libraries-templates) is the section for libraries and templates, which, although I'm not entirely sure, is just a place to share projects with a cover, kind of on how Figma does it.

Thanks for your time and for this amazing project!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/436">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/436/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/436/pledge.svg">
</picture>
</a>

**Comment by lucaburgio** [comment]
Iconoir is already available on PenPot https://penpot.app/libraries-templates
