### ISSUE TITLE
[ICON] - External Link

### ISSUE THREAD

**Issue by ridgehkr** [iconoir-icons/iconoir#445]
## Icon Request

* Icon name: External Link
* Use case: Indicate that a link will take the user to an external site
* Screenshots of similar icons:

![image](https://github.com/iconoir-icons/iconoir/assets/1012241/22137a73-bee8-4f8d-9524-38e2f3dadf73)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/445">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/445/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/445/pledge.svg">
</picture>
</a>

**Comment by paescuj** [comment]
I think you're looking for `open-new-window` 👍

**Comment by ridgehkr** [comment]
> I think you're looking for `open-new-window` 👍

My mistake! Thanks
