### ISSUE TITLE
Ellipsis/More Icons, Distorted if stroke > 2

### ISSUE THREAD

**Issue by james-william-r** [iconoir-icons/iconoir#461]
## Prerequisites

* Version: 7.7.0
* Are you running from source/main: Yes
* Are you using a released build: Yes
* Operating system: MacOS 14.4.1 (23E224)

## Step to reproduce

Set the stroke with of any of the more/ellipsis icons > 2 (although most obvious when > 3).

### Actual behavior

It looks as though the dots are tiny outlined circles, as oppose to solid dots.

## Any message or error

N/A

## Additional info or screenshots

* Screenshots
<img width="737" alt="Screenshot 2024-07-06 at 10 20 01 PM" src="https://github.com/iconoir-icons/iconoir/assets/66140148/92086c74-820e-4a30-b775-97f27a1ef24a">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/461">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/461/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/461/pledge.svg">
</picture>
</a>

**Comment by james-william-r** [comment]
Oh, strange... When downloaded and imported into Adobe Illustrator, they look totally fine... which made me check their appearance in a different browser and it seems the issue is unique to Arc. - So, can probs close this issue, as don't think it's on Iconoir's end.

**Comment by lucaburgio** [comment]
Confirming it looks on the Arc's side. Closing it for now 🙌
