### ISSUE TITLE
[ICON] Calendar with Download Arrow

### ISSUE THREAD

**Issue by alexandreclalex** [iconoir-icons/iconoir#468]
## Icon Request

* Icon name: calendar-download
* Use case: Download button for a calendatr
* Screenshots of similar icons: 
![calendar-download](https://github.com/user-attachments/assets/aa8e63a7-4f01-413f-8505-996c1722ef22)
This is what I am currently using for this purpose, made by adding a downwards arrow to calendar-minus.
Feel free to add this icon to the repo

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/iconoir-icons) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/iconoir-icons/iconoir/issues/468">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/iconoir-icons/iconoir/issues/468/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/iconoir-icons/iconoir/issues/468/pledge.svg">
</picture>
</a>

**Comment by lucaburgio** [comment]
released in `v7.9.0`
